------------------------------------------------------------------------------
						--Magnitude Analaysis
------------------------------------------------------------------------------
------------------------------------------------------------------------------
				---Find the total sales by each category
------------------------------------------------------------------------------
select P.category,
SUM(G.Sales_Amount) as Total_sales_by_each_Category 
from Gold.fact_sales G
left join gold.dim_products p
on G.Product_Key = P.product_key
group by p.Category
order by Total_sales_by_each_Category  DESC

------------------------------------------------------------------------------
			---Find the total sales by each Country
------------------------------------------------------------------------------
select C.Country,
SUM(G.Sales_Amount) as Total_sales_by_each_Country
from Gold.fact_sales G
left join gold.dim_customers C
on G.Customer_key = C.Customer_key
group by C.Country
order by Total_sales_by_each_Country DESC

------------------------------------------------------------------------------
		---Find the total no. of customers by each Country
------------------------------------------------------------------------------
select Country,
COUNT(distinct Customer_id) as Total_customers_by_each_country
from Gold.dim_customers
group by Country
order by Total_customers_by_each_country DESC

------------------------------------------------------------------------------
		---Find the total no. of customers  by gender
------------------------------------------------------------------------------
select Gender,
COUNT(distinct Customer_id) as Total_customers_by_gender
from Gold.dim_customers
group by Gender
order by Total_customers_by_gender DESC

------------------------------------------------------------------------------
		---Find the total no. of products by each Category
------------------------------------------------------------------------------
select Category,
COUNT(distinct Product_id) as Total_products_by_Category
from Gold.dim_products
group by Category
order  by Total_products_by_Category Desc

------------------------------------------------------------------------------
			---Find the avg price in each category
------------------------------------------------------------------------------
select P.Category,
AVG(price) as Avg_Price
from Gold.fact_sales S
Left join Gold.dim_products P
on S.Product_key = P.Product_key
group by P.Category 
order by Avg_Price DESC

------------------------------------------------------------------------------
		--what is total revenue generated by each category
------------------------------------------------------------------------------
select P.category,
SUM(sales_amount) as Total_Revenue
from Gold.fact_sales S
left join Gold.dim_products P 
on S.Product_Key = P.Product_Key
group by P.Category
order by Total_Revenue DESC

------------------------------------------------------------------------------
		--find total revnue genrated by each customer
------------------------------------------------------------------------------
select C.Customer_key,C.Full_Name,
SUM(sales_amount) as Total_Revenue
from Gold.fact_sales S
left join Gold.dim_customers C 
on S.Customer_key = C.Customer_key
group by C.Customer_key,
C.Full_Name
order by Total_Revenue DESC

--------------------------------------------------------------------------
	--what is the distribution of sold items in each countries 
--------------------------------------------------------------------------
select C.Country,
SUM(G.Quantity) as Total_Sold_items_by_Country
from Gold.fact_sales G
left join gold.dim_customers C
on G.Customer_key = C.Customer_key
group by C.Country
order by Total_Sold_items_by_Country  DESC
